#!/bin/sh
rm script_log.txt
# Add logging
log_file="script_log.txt"
exec > >(tee -a "$log_file") 2>&1
echo "Script started at $(date)"

DIR=$1
echo "First image: " $DIR/00001.jpg
echo "Transparent video place on top of video as overlay" comic_frame_b-512x768.png
melt \
  $DIR/00001.jpg in=0 out=60 -mix 60 \
  $DIR/00002.jpg in=60 out=120 -mix 60 \
  $DIR/00003.jpg in=120 out=180 -mix 60 \
  $DIR/00004.jpg in=180 out=240 -mix 60 \
  $DIR/00005.jpg in=240 out=300 -mix 60 \
  $DIR/00006.jpg in=300 out=360 -mix 60 \
  $DIR/00007.jpg in=360 out=420 -mix 60 \
  $DIR/00008.jpg in=420 out=480 -mix 60 \
  $DIR/00009.jpg in=480 out=540 -mix 60 \
  $DIR/00010.jpg in=540 out=600 -mix 60 \
  $DIR/00011.jpg in=600 out=660 -mix 60 \
  $DIR/00012.jpg in=660 out=720 -mix 60 \
  $DIR/00013.jpg in=720 out=780 -mix 60 \
  $DIR/00014.jpg in=780 out=840 -mix 60 \
  $DIR/00015.jpg in=840 out=900 -mix 60 \
  $DIR/00016.jpg in=900 out=960 -mix 60 \
  $DIR/00017.jpg in=960 out=1020 -mix 60 \
  $DIR/00018.jpg in=1020 out=1080 -mix 60 \
  $DIR/00019.jpg in=1080 out=1140 -mix 60 \
  $DIR/00020.jpg in=1140 out=1200 -mix 60 \
  -mix 60 \
  -attach comic_frame_b-512x768.png -geometry "0x0" -mix 60 -track \
  -consumer avformat:final_video3.mp4

# Add logging
echo "Script completed at $(date)"
echo "Log file: $log_file"
sub=/opt/sublime_text/sublime_text
$sub script_log.txt
vlc final_video3.mp4
